#!/bin/bash

# Base directory
BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Useful directory locations
CONFIG_DIR=$BASE_DIR'/config/'
BUILDROOT_DIR=$BASE_DIR'/buildroot-2018.02.4/'

# Useful file locations
CONFIG_FILENAME='buildroot.config'
BUILDROOT_CONFIG_FILENAME='.config'

printusage() {
    echo "Usage: $0 [-h] [-t target]"
    echo "  -h, --help   | Print usage text"
    echo "  -t, --target | Target to build"
}

checkroot() {
    if [ "$EUID" -eq 0 ]; then
        echo "Root privileges detected. Stopping build."
        exit 0
    fi
}

################################################################################
# Main script calls go here
################################################################################
RUN_BUILD_TARGET=false
RUN_HELP=false
POSITIONAL=()

# Check for root
checkroot

while [[ $# -gt 0 ]]
do
    key="$1"

    case $key in 
        -t|--target)
            RUN_BUILD_TARGET=true
            BUILD_TARGET_ARGUMENT=$2
            # Shift past both arguments
            shift
            shift
            ;;
        -h|--help)
            RUN_HELP=true
            shift
            ;;
        *)
            echo "Argument $1 is invalid"
            POSITIONAL+=("$1")
            shift
            exit 1
            ;;
    esac 
done

# restore positional parameters
set -- "${POSITIONAL[@]}"

# Run the help option
if $RUN_HELP; then
    # Print the usage text and then exit
    printusage
    exit 0
fi

# Run the target option
if $RUN_BUILD_TARGET; then
    echo "Building target $BUILD_TARGET_ARGUMENT"

    # Check if the config directory exists
    CONFIG_TARGET_DIR=$CONFIG_DIR$BUILD_TARGET_ARGUMENT'/'
    if [ -d $CONFIG_TARGET_DIR ]; then
        echo "Target directory exists: $CONFIG_TARGET_DIR"
    else
        echo "Directory does NOT exist: $CONFIG_TARGET_DIR"
        exit 1
    fi

    # Check if the buildroot config exists for the target
    CONFIG_TARGET_FILE=$CONFIG_TARGET_DIR$CONFIG_FILENAME
    if [ -f $CONFIG_TARGET_FILENAME ]; then
        echo "Target config file exists!"
        TARGET_BUILD_DIR=$BASE_DIR"/target-$BUILD_TARGET_ARGUMENT/"
        mkdir -p $TARGET_BUILD_DIR
        cp $CONFIG_TARGET_FILE $TARGET_BUILD_DIR'/'$BUILDROOT_CONFIG_FILENAME
        ( cd $TARGET_BUILD_DIR && make O=$TARGET_BUILD_DIR -C $BUILDROOT_DIR )
    else
        echo "File does NOT exist: $CONFIG_TARGET_FILE"
    fi

fi
